import { formatDMY, weekdayOf } from "./format";
import type { AttendanceRangeRow, AttendanceStatus } from "./types";

/** The statuses every attendance report breaks out, in column order. */
export const REPORT_STATUSES: AttendanceStatus[] = [
  "Present",
  "Late",
  "Half Day",
  "Absent",
  "Leave",
  "Pending Checkout",
];

/** Column heading for a status — "Pending Checkout" is too wide for a column. */
export function statusColumnLabel(status: AttendanceStatus): string {
  return status === "Pending Checkout" ? "No Checkout" : status;
}

/**
 * "August 2026" when [from, to] covers exactly one calendar month, else "".
 * Lets the report title say the month when there is one, without pretending
 * a hand-picked 10-day range is a month.
 */
export function monthTitleOf(from: string, to: string): string {
  if (!from || !to) return "";
  const [fy, fm, fd] = from.split("-").map(Number);
  const [ty, tm] = to.split("-").map(Number);
  if (fd !== 1 || fy !== ty || fm !== tm) return "";
  return new Date(fy!, fm! - 1, 1).toLocaleDateString("en-IN", { month: "long", year: "numeric" });
}

/** "August 2026" -> "august-2026"; anything else falls back to the raw dates. */
function fileSlug(text: string): string {
  return text.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase();
}

export interface AttendanceReportOptions {
  /** Rows exactly as shown on screen — already filtered by employee if one is picked. */
  rows: AttendanceRangeRow[];
  from: string;
  to: string;
  /** Name shown on the "Generated by" line. */
  generatedBy: string;
}

/**
 * Builds the monthly attendance report as a PDF and hands it straight to the
 * browser's downloader — no print dialog, no intermediate preview.
 *
 * jsPDF is imported here rather than at module scope so the ~350KB library is
 * only fetched when someone actually clicks Export, and never ships in the
 * page's initial bundle. Text is drawn in Helvetica, so employee names are
 * expected to be in the Latin alphabet (as they are throughout the app).
 */
export async function downloadAttendancePdf({
  rows,
  from,
  to,
  generatedBy,
}: AttendanceReportOptions): Promise<void> {
  const [{ jsPDF }, { autoTable }] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);

  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;

  const monthTitle = monthTitleOf(from, to);
  const single = rows.length === 1 ? rows[0] : null;

  // --- letterhead ---------------------------------------------------------
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("THIRTY MILESTONES", margin, 52);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Monthly Attendance Report", pageWidth - margin, 52, { align: "right" });
  doc.setLineWidth(1.2);
  doc.line(margin, 62, pageWidth - margin, 62);

  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  const generatedAt =
    `${pad(now.getDate())}-${pad(now.getMonth() + 1)}-${now.getFullYear()} ` +
    `${pad(now.getHours())}:${pad(now.getMinutes())}`;
  const meta: Array<[string, string]> = [
    ["Period", `${formatDMY(from)} to ${formatDMY(to)}${monthTitle ? `  (${monthTitle})` : ""}`],
    ["Employees", single ? single.employee.name : `All employees (${rows.length})`],
    ["Generated", `${generatedAt} by ${generatedBy || "—"}`],
  ];
  let y = 82;
  for (const [label, value] of meta) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(label.toUpperCase(), margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, margin + 70, y);
    y += 14;
  }

  // --- shared table styling ----------------------------------------------
  /** Draws one table and returns the y it finished at. */
  function drawTable(options: Parameters<typeof autoTable>[1]): number {
    let finalY = typeof options.startY === "number" ? options.startY : y;
    autoTable(doc, {
      theme: "grid",
      styles: { font: "helvetica", fontSize: 9, cellPadding: 5, lineColor: [0, 0, 0], lineWidth: 0.5 },
      headStyles: { fillColor: [0, 0, 0], textColor: 255, fontStyle: "bold" },
      margin: { left: margin, right: margin, top: margin, bottom: margin + 20 },
      ...options,
      // Only tracks where the table ended; footers are drawn once at the end,
      // otherwise each table on a page would stamp another one on top.
      didDrawPage: (data) => {
        if (data.cursor) finalY = data.cursor.y;
      },
    });
    return finalY;
  }

  function sectionHeading(title: string, atY: number): number {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(title.toUpperCase(), margin, atY);
    return atY + 8;
  }

  // --- summary ------------------------------------------------------------
  const totals = REPORT_STATUSES.map((status) =>
    rows.reduce((sum, r) => sum + (r.counts?.[status] ?? 0), 0)
  );
  const totalMarked = rows.reduce((sum, r) => sum + (r.totalMarked ?? 0), 0);

  y = sectionHeading("Summary", y + 14);
  y = drawTable({
    startY: y,
    head: [[...REPORT_STATUSES.map(statusColumnLabel), "Total Marked"]],
    body: [[...totals.map(String), String(totalMarked)]],
    styles: { font: "helvetica", fontSize: 9, cellPadding: 5, halign: "center", lineColor: [0, 0, 0], lineWidth: 0.5 },
  });

  // --- employee-wise ------------------------------------------------------
  y = sectionHeading("Employee-wise", y + 24);
  y = drawTable({
    startY: y,
    head: [["#", "Employee", ...REPORT_STATUSES.map(statusColumnLabel), "Total"]],
    body: rows.map((r, i) => [
      String(i + 1),
      r.employee.name,
      ...REPORT_STATUSES.map((status) => String(r.counts?.[status] ?? 0)),
      String(r.totalMarked ?? 0),
    ]),
    columnStyles: { 0: { halign: "center", cellWidth: 26 }, 1: { cellWidth: 120 } },
    // Everything but the name column reads as a number.
    didParseCell: (data) => {
      if (data.column.index > 1) data.cell.styles.halign = "center";
    },
    foot: [["", "Total", ...totals.map(String), String(totalMarked)]],
    footStyles: { fillColor: [235, 235, 235], textColor: 0, fontStyle: "bold", halign: "center" },
    showFoot: "lastPage",
  });

  // --- day-wise detail, only when the report is about one person ----------
  const detail = single
    ? REPORT_STATUSES.flatMap((status) =>
        (single.dates?.[status] ?? []).map((date) => ({ date, status }))
      ).sort((a, b) => a.date.localeCompare(b.date))
    : [];

  if (detail.length > 0) {
    y = sectionHeading(`Day-wise detail — ${single!.employee.name}`, y + 24);
    drawTable({
      startY: y,
      head: [["Date", "Day", "Status"]],
      body: detail.map((d) => [formatDMY(d.date), weekdayOf(d.date), d.status]),
      columnStyles: { 0: { cellWidth: 90 }, 1: { cellWidth: 90 } },
    });
  }

  // Footers last, when the real page count is known.
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page++) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(`Page ${page} of ${pageCount}`, margin, pageHeight - margin + 12);
    doc.text("Thirty Milestones · Attendance", pageWidth - margin, pageHeight - margin + 12, {
      align: "right",
    });
  }

  const scope = single ? `${fileSlug(single.employee.name)}-` : "";
  const period = monthTitle ? fileSlug(monthTitle) : `${from}-to-${to}`;
  doc.save(`attendance-${scope}${period}.pdf`);
}
